// <auto-generated />
namespace Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Removendo_amigos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removendo_amigos));
        
        string IMigrationMetadata.Id
        {
            get { return "201912090123549_Removendo_amigos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
