// <auto-generated />
namespace Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class update1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update1));
        
        string IMigrationMetadata.Id
        {
            get { return "201912101823041_update1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
